//
//  Decks.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class Decks: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String!
    var _cards: Set<String>!
    var _name: String!
    
    class func dynamoDBTableName() -> String {

        return "hatsimulator-mobilehub-2006432269-Decks"
    }
    
    class func hashKeyAttribute() -> String {

        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_id" : "id",
               "_cards" : "cards",
               "_name" : "name",
        ]
    }
}
